#ifndef FEATURE_BASED_TEMPLATE_MATCHING_3_1_H__
#define FEATURE_BASED_TEMPLATE_MATCHING_3_1_H__

enum DetectorType {
    DETECTOR_SIFT = 0,
    DETECTOR_SURF,
    DETECTOR_KAZE,
    DETECTOR_AKAZE,
    DETECTOR_ORB,
    DETECTOR_BRISK,
    DETECTOR_AGAST,
    DETECTOR_FAST,
    DETECTOR_GFTT,
    DETECTOR_SIZE
};

enum MatcherType {
    MATCHER_FLANN = 0,
    MATCHER_BF,
    MATCHER_SIZE
};

enum CommandType {
    CMD_DETECT = 0,
    CMD_DETECT_AND_MATCH,
    CMD_SIZE
};

#endif
